FROM confluentinc/cp-kafka:latest
# USER root
# RUN dnf update -y && \
#     dnf install -y bash net-tools iputils python3 python3-pip && \
#     pip3 install --upgrade pip && \
#     pip3 install importlib_metadata confluent-docker-utils && \
#     dnf clean all

# USER appuser

